# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )

### Images
# Landing Page
Rails.application.config.assets.precompile += %w( favicon.png )
Rails.application.config.assets.precompile += %w( logo/apple-appstore.svg )
Rails.application.config.assets.precompile += %w( icon/back-button.png )
Rails.application.config.assets.precompile += %w( iphone-skeleton.png )
Rails.application.config.assets.precompile += %w( stock/people.jpg )
Rails.application.config.assets.precompile += %w( preview/party-info.png )
Rails.application.config.assets.precompile += %w( map-berkeley.png )

# Profile Page
Rails.application.config.assets.precompile += %w( profile/sf-background.png )
Rails.application.config.assets.precompile += %w( stock/default_profile_picture.png )
Rails.application.config.assets.precompile += %w( icon/pin-expired.png )
Rails.application.config.assets.precompile += %w( icon/icon-pin.png )
Rails.application.config.assets.precompile += %w( icon/icon-time.png )
Rails.application.config.assets.precompile += %w( icon/pulse.png )
Rails.application.config.assets.precompile += %w( icon/my-twing.png )
Rails.application.config.assets.precompile += %w( icon/my-friend.png )
Rails.application.config.assets.precompile += %w( icon/notif-bubble.png )
Rails.application.config.assets.precompile += %w( icon/new-pin.png )
Rails.application.config.assets.precompile += %w( logo/thumbnail-default.png )
Rails.application.config.assets.precompile += %w( logo/thumbnail-camera.png )
Rails.application.config.assets.precompile += %w( logo/thumbnail-upload.png )

Rails.application.config.assets.precompile += %w( pins/0.png )
Rails.application.config.assets.precompile += %w( pins/1.png )
Rails.application.config.assets.precompile += %w( pins/2.png )
Rails.application.config.assets.precompile += %w( pins/3.png )
Rails.application.config.assets.precompile += %w( pins/4.png )
Rails.application.config.assets.precompile += %w( pins/5.png )
Rails.application.config.assets.precompile += %w( pins/6.png )
Rails.application.config.assets.precompile += %w( pins/7.png )
Rails.application.config.assets.precompile += %w( pins/8.png )
Rails.application.config.assets.precompile += %w( pins/9.png )
Rails.application.config.assets.precompile += %w( pins/10.png )
Rails.application.config.assets.precompile += %w( pins/11.png )
Rails.application.config.assets.precompile += %w( pins/12.png )
Rails.application.config.assets.precompile += %w( pins/13.png )
Rails.application.config.assets.precompile += %w( pins/14.png )
Rails.application.config.assets.precompile += %w( pins/15.png )
Rails.application.config.assets.precompile += %w( pins/16.png )
Rails.application.config.assets.precompile += %w( pins/17.png )
Rails.application.config.assets.precompile += %w( pins/18.png )
Rails.application.config.assets.precompile += %w( pins/19.png )
Rails.application.config.assets.precompile += %w( pins/20.png )
Rails.application.config.assets.precompile += %w( pins/21.png )
Rails.application.config.assets.precompile += %w( pins/22.png )
Rails.application.config.assets.precompile += %w( pins/23.png )
Rails.application.config.assets.precompile += %w( pins/24.png )
Rails.application.config.assets.precompile += %w( pins/25.png )
Rails.application.config.assets.precompile += %w( pins/26.png )
Rails.application.config.assets.precompile += %w( pins/27.png )
Rails.application.config.assets.precompile += %w( pins/28.png )
Rails.application.config.assets.precompile += %w( pins/29.png )
Rails.application.config.assets.precompile += %w( pins/30.png )
Rails.application.config.assets.precompile += %w( pins/31.png )
Rails.application.config.assets.precompile += %w( pins/32.png )
Rails.application.config.assets.precompile += %w( pins/33.png )
Rails.application.config.assets.precompile += %w( pins/34.png )
Rails.application.config.assets.precompile += %w( pins/35.png )
Rails.application.config.assets.precompile += %w( pins/36.png )
Rails.application.config.assets.precompile += %w( pins/37.png )
Rails.application.config.assets.precompile += %w( pins/38.png )
Rails.application.config.assets.precompile += %w( pins/39.png )
Rails.application.config.assets.precompile += %w( pins/40.png )
Rails.application.config.assets.precompile += %w( pins/41.png )
Rails.application.config.assets.precompile += %w( pins/42.png )
Rails.application.config.assets.precompile += %w( pins/43.png )
Rails.application.config.assets.precompile += %w( pins/44.png )
Rails.application.config.assets.precompile += %w( pins/45.png )
Rails.application.config.assets.precompile += %w( pins/46.png )
Rails.application.config.assets.precompile += %w( pins/47.png )
Rails.application.config.assets.precompile += %w( pins/48.png )
Rails.application.config.assets.precompile += %w( pins/49.png )
Rails.application.config.assets.precompile += %w( pins/50.png )
Rails.application.config.assets.precompile += %w( pins/51.png )
Rails.application.config.assets.precompile += %w( pins/52.png )
Rails.application.config.assets.precompile += %w( pins/53.png )
Rails.application.config.assets.precompile += %w( pins/54.png )
Rails.application.config.assets.precompile += %w( pins/55.png )
Rails.application.config.assets.precompile += %w( pins/56.png )
Rails.application.config.assets.precompile += %w( pins/57.png )
Rails.application.config.assets.precompile += %w( pins/58.png )
Rails.application.config.assets.precompile += %w( pins/59.png )
Rails.application.config.assets.precompile += %w( pins/60.png )
Rails.application.config.assets.precompile += %w( pins/61.png )
Rails.application.config.assets.precompile += %w( pins/62.png )
Rails.application.config.assets.precompile += %w( pins/63.png )
Rails.application.config.assets.precompile += %w( pins/64.png )
Rails.application.config.assets.precompile += %w( pins/65.png )
Rails.application.config.assets.precompile += %w( pins/66.png )
Rails.application.config.assets.precompile += %w( pins/67.png )
Rails.application.config.assets.precompile += %w( pins/68.png )
Rails.application.config.assets.precompile += %w( pins/69.png )
Rails.application.config.assets.precompile += %w( pins/70.png )
Rails.application.config.assets.precompile += %w( pins/71.png )
Rails.application.config.assets.precompile += %w( pins/72.png )
Rails.application.config.assets.precompile += %w( pins/73.png )
Rails.application.config.assets.precompile += %w( pins/74.png )
Rails.application.config.assets.precompile += %w( pins/75.png )
Rails.application.config.assets.precompile += %w( pins/76.png )
Rails.application.config.assets.precompile += %w( pins/77.png )
Rails.application.config.assets.precompile += %w( pins/78.png )
Rails.application.config.assets.precompile += %w( pins/79.png )
Rails.application.config.assets.precompile += %w( pins/80.png )
Rails.application.config.assets.precompile += %w( pins/81.png )
Rails.application.config.assets.precompile += %w( pins/82.png )
Rails.application.config.assets.precompile += %w( pins/83.png )
Rails.application.config.assets.precompile += %w( pins/84.png )
Rails.application.config.assets.precompile += %w( pins/85.png )
Rails.application.config.assets.precompile += %w( pins/86.png )
Rails.application.config.assets.precompile += %w( pins/87.png )
Rails.application.config.assets.precompile += %w( pins/88.png )
Rails.application.config.assets.precompile += %w( pins/89.png )
Rails.application.config.assets.precompile += %w( pins/90.png )
Rails.application.config.assets.precompile += %w( pins/91.png )
Rails.application.config.assets.precompile += %w( pins/92.png )
Rails.application.config.assets.precompile += %w( pins/93.png )
Rails.application.config.assets.precompile += %w( pins/94.png )
Rails.application.config.assets.precompile += %w( pins/95.png )
Rails.application.config.assets.precompile += %w( pins/96.png )
Rails.application.config.assets.precompile += %w( pins/97.png )
Rails.application.config.assets.precompile += %w( pins/98.png )
Rails.application.config.assets.precompile += %w( pins/99.png )
Rails.application.config.assets.precompile += %w( pins/100.png )
Rails.application.config.assets.precompile += %w( pins/101.png )






### Stylesheets
# Landing Page Temporary
Rails.application.config.assets.precompile += %w( temporaryIndex.css )

# Landing Page
Rails.application.config.assets.precompile += %w( bootstrap.min.css )
Rails.application.config.assets.precompile += %w( flickity.css )
Rails.application.config.assets.precompile += %w( animate.css )
Rails.application.config.assets.precompile += %w( styles.css )
Rails.application.config.assets.precompile += %w( queries.css )
Rails.application.config.assets.precompile += %w( slick.css )
Rails.application.config.assets.precompile += %w( slick-theme.css )
Rails.application.config.assets.precompile += %w( design.css )
Rails.application.config.assets.precompile += %w( sprites.css )


### Javascripts
# Landing Page
Rails.application.config.assets.precompile += %w( flickity.pkgd.min.js )
Rails.application.config.assets.precompile += %w( waypoints.min.js )
Rails.application.config.assets.precompile += %w( bootstrap.min.js )
Rails.application.config.assets.precompile += %w( typed.min.js )
Rails.application.config.assets.precompile += %w( scripts.js )

# Profile Page
Rails.application.config.assets.precompile += %w( pins-url.js )
Rails.application.config.assets.precompile += %w( scripts-profile.js )
Rails.application.config.assets.precompile += %w( slick.js )